TrainingAppAspCore/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TrainingAppAspCore.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

TrainingAppAspCore/Pages/ClientWorkouts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TrainingAppAspCore.Dto;
using Microsoft.Extensions.Logging;

namespace TrainingAppAspCore.Pages
{
    public class ClientWorkoutsModel : PageModel
    {
        public string ClientName { get; set; }
        public int ClientId { get; set; }
        IExecuteTrainingHttpClient ExecuteHttpClient;
        public List<ClientWorkoutDto> ClientWorkouts { get; set; }
        private string ClientObjectIdentifier = "";
        private ILogger _logger;

        public ClientWorkoutsModel(IExecuteTrainingHttpClient executeTrainingClient, ILogger<ClientWorkoutsModel> logger)
        {
            ExecuteHttpClient = executeTrainingClient;
            _logger = logger;
        }

        public async Task OnGet()
        {
            try
            {
                ClientWorkouts = new List<ClientWorkoutDto>();
                // get ClientObjectIdentifier from knowing User.Identities
                var identity = (ClaimsIdentity)User.Identity;
                var claims = identity.Claims;
                ClientObjectIdentifier = claims.Where(e => e.Type == ClaimTypes.NameIdentifier)
                                    .Select(s => s.Value).FirstOrDefault();

                ClientId = await GetClient(ClientObjectIdentifier);

                // put ClientId into cookie for use across all requests
                HttpContext.Response.Cookies.Append("ClientId", ClientId.ToString());

                //first time login so create entry into database
                if (ClientId == 0 && !string.IsNullOrEmpty(ClientObjectIdentifier))
                {
                    //add client to database
                    var name = claims.Where(e => e.Type == "name").Select(s => s.Value).First();
                    var email = claims.Where(e => e.Type == "emails").Select(s => s.Value).First();

                    var newClient = new ClientDto()
                    {
                        FirstName = name,
                        Email = email,
                        ObjectIdentifier = ClientObjectIdentifier,
                    };
                    var clientDto = await PostClient(newClient);

                    ClientId = clientDto.ClientId;
                    // put ClientId into cookie for use across all requests
                    HttpContext.Response.Cookies.Append("ClientId", ClientId.ToString());
                }

                if (ClientId != 0)
                {
                    await GetClientWorkouts();
                }

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Get ClientWorkout");
            }

        }

        public async Task<Boolean> GetClientWorkouts()
        {
            var HttpClient = ExecuteHttpClient;
            ClientWorkouts = await HttpClient.ExecuteRoute<List<ClientWorkoutDto>>(HttpMethod.Get, RouteUri.UriClientWorkoutsById(ClientId));
            var ClientDto = await HttpClient.ExecuteRoute<ClientDto>(HttpMethod.Get, RouteUri.UriClientById(ClientId));
            ClientName = ClientDto != null ? "Hi " + ClientDto.FirstName : "Please Log In";
            return true;
        }

        public async Task<int> GetClient(string clientObjectIdentifier)
        {
            var HttpClient = ExecuteHttpClient;
            ClientDto clientQuery = new ClientDto()
            {
                ObjectIdentifier = clientObjectIdentifier,
            };
            var ClientDto = await HttpClient.ExecuteRoute<ClientDto>(HttpMethod.Post, RouteUri.UriClientQuery, clientQuery);
            var clientId = ClientDto == null ? 0 : ClientDto.ClientId;
            ClientName = ClientDto != null ? "Hi " + ClientDto.FirstName : "Please Log In";
            return clientId;
        }

        public async Task<ClientDto> PostClient(ClientDto newClient)
        {
            var HttpClient = ExecuteHttpClient;

            var ClientDto = await HttpClient.ExecuteRoute<ClientDto>(HttpMethod.Post, RouteUri.UriClients, newClient);
            ClientId = ClientDto == null ? 0 : ClientDto.ClientId;
            if(ClientId == 0)
            {
                ClientDto = new ClientDto();
            }
            return ClientDto;
        }
    }
}

TrainingAppAspCore/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TrainingAppAspCore.Pages
{
    public class ContactModel : PageModel
    {
        public string MessageContact { get; set; }
        public string MessageAbout { get; set; }

        public void OnGet()
        {
            MessageContact = "Need some support please email";
            MessageAbout = "Deadpan Melbourne Hipster writing semi-useful applications";
        }
    }
}

TrainingAppAspCore/Pages/CreateWorkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TrainingAppAspCore.Dto;
using Microsoft.Extensions.Logging;

namespace TrainingAppAspCore.Pages
{
    public class CreateWorkoutModel : PageModel
    {
        IExecuteTrainingHttpClient ExecuteHttpClient;
        public List<WorkoutPlanDto> Workouts { get; set; }
        public int ClientId { get; set; }
        public string ErrorMessage { get; set; }
        private ILogger _logger;

        public CreateWorkoutModel(IExecuteTrainingHttpClient executeTrainingClient, ILogger<CreateWorkoutModel> logger)
        {
            ExecuteHttpClient = executeTrainingClient;
            _logger = logger;
        }

        public async Task OnGet()
        {
            try
            {
               var Client = ExecuteHttpClient;
               Workouts = await Client.ExecuteRoute<List<WorkoutPlanDto>>(HttpMethod.Get, RouteUri.UriWorkoutPlans);

                //clientID from cookie
                ClientId = int.Parse(HttpContext.Request.Cookies["ClientId"]);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Get WorkoutPlan");
            }
            TempData["ErrorMessage"] = string.Empty;
        }
        public async Task OnGetModal()
        {
            try
            {
                var Client = ExecuteHttpClient;
                Workouts = await Client.ExecuteRoute<List<WorkoutPlanDto>>(HttpMethod.Get, RouteUri.UriWorkoutPlans);

                ClientId = int.Parse(HttpContext.Request.Cookies["ClientId"].ToString());
                ErrorMessage = TempData["ErrorMessage"].ToString();
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in GetModal Return to WorkoutPlan");
            }
        }

        public async Task<ActionResult> OnPostAddWorkoutClient() 
        {
            try
            {
                //get workoutPlanId & clientId
                var workoutplanId =  int.Parse(PageContext.HttpContext.Request.Query["Id"].ToString());
                ClientId = int.Parse(HttpContext.Request.Cookies["ClientId"]);
                var frequency = int.Parse(HttpContext.Request.Form["frequency"]);

                //create dto to post
                AddClientWorkoutDto addClientWorkoutDto = new AddClientWorkoutDto()
                {
                    ClientId = ClientId,
                    Frequency = frequency,
                    WorkoutPlanId = workoutplanId,
                };

                var Client = ExecuteHttpClient;
                var clientWorkouts = await Client.ExecuteRoute<ClientWorkoutDto>(HttpMethod.Post, RouteUri.UriClientWorkouts,addClientWorkoutDto);

                if(Client.HttpStatusCode != System.Net.HttpStatusCode.OK)
                {
                    //error with Post                
                    ErrorMessage = Client.ReturnedError;
                    //TempData["ErrorMessage"] = ErrorMessage;
                    TempData["ErrorMessage"] = ErrorMessage;
                    TempData["CallingPage"]="CreateWorkout";
                    return RedirectToPage("Error");
                    //return RedirectToPage("CreateWorkout","Modal");
                }
                else
                {
                    return RedirectToPage("ClientWorkouts");
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Post Add Client WorkoutPlan");
                throw;
            }
        }
    }
}

TrainingAppAspCore/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TrainingAppAspCore.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => false;//!string.IsNullOrEmpty(RequestId);
        public string ErrorMessage { get; set; }
        public string CallingPage { get; set; }
       // public int CallingIdForGet { get; set; }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            ErrorMessage = TempData["ErrorMessage"].ToString() ?? string.Empty;
            CallingPage = TempData["CallingPage"].ToString() ?? string.Empty;
           
        }
    }
}

TrainingAppAspCore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TrainingAppAspCore.Pages
{

    public class IndexModel : PageModel
    {
        IExecuteTrainingHttpClient ExecuteHttpClient;


        public IndexModel(IExecuteTrainingHttpClient executeTrainingClient)
        {
            ExecuteHttpClient = executeTrainingClient;
        }
       

    }
}

TrainingAppAspCore/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.AzureADB2C.UI;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace TrainingAppAspCore.Pages
{
    //NOT IN USE 
    public class LogoutModel : PageModel
    {
        public async Task<ActionResult> OnGet()
        {

           string scheme =  AzureADB2CDefaults.AuthenticationScheme;
            var authenticated = await HttpContext.AuthenticateAsync(scheme);
            if (!authenticated.Succeeded)
            {
                return Challenge(scheme);
            }

            var options = new AzureADB2COptions();

            var callbackUrl = Url.Page("/Index", pageHandler: null, values: null, protocol: Request.Scheme);
            var result = SignOut(new AuthenticationProperties { RedirectUri = callbackUrl }, scheme);

            return RedirectToPage("Index");

        }
    }
}
 

TrainingAppAspCore/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TrainingAppAspCore.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TrainingAppAspCore/Pages/StartExercises.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TrainingAppAspCore.Dto;
using Microsoft.Extensions.Logging;

namespace TrainingAppAspCore.Pages
{
    public class StartExerciseModel : PageModel
    {
        IExecuteTrainingHttpClient ExecuteHttpClient;
        public List<ExerciseDto> Exercises { get; set; }
        public int ClientId { get; set; }
        public int WorkoutPlanId { get; set; }
        public string ErrorMessage { get; set; }
        private ILogger _logger;

        public StartExerciseModel(IExecuteTrainingHttpClient executeTrainingClient, ILogger<StartExerciseModel> logger)
        {
            ExecuteHttpClient = executeTrainingClient;
            _logger = logger;
        }

        public async Task OnGet()
        {
            try
            {
               //get workoutplanID from request
               WorkoutPlanId = int.Parse(HttpContext.Request.Query["Id"]);

               var Client = ExecuteHttpClient;
               var workoutExercise = await Client.ExecuteRoute<List<WorkoutExerciseDto>>(HttpMethod.Get, RouteUri.UriWorkoutExercises);

                Exercises = workoutExercise.Where(w => w.WorkoutPlanId == WorkoutPlanId)
                              .Select(s => s.Exercise).ToList();
               
               // ClientId = int.Parse(HttpContext.Request.Cookies["ClientId"]);

                //TODO get reps & weight for each exercise - probs best do in api
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Get WorkoutExercise");
            }

        }

    }
}

TrainingAppAspCore/Pages/WorkoutExercise.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TrainingAppAspCore.Dto;
using Microsoft.Extensions.Logging;

namespace TrainingAppAspCore.Pages
{
    public class WorkoutExerciseModel : PageModel
    {
        IExecuteTrainingHttpClient ExecuteHttpClient;
        public List<WorkoutExerciseDto> WorkoutExercise { get; set; }
        public List<ExerciseDto> Exercises { get; set; }
        public int workoutplanId { get; set; }
        private ILogger _logger;

        public WorkoutExerciseModel(IExecuteTrainingHttpClient executeTrainingClient, ILogger<WorkoutExerciseModel> logger)
        {
            ExecuteHttpClient = executeTrainingClient;
            _logger = logger;
        }

        public async Task OnGet()
        {
            try
            {
                var Client = ExecuteHttpClient;
                WorkoutExercise = await Client.ExecuteRoute<List<WorkoutExerciseDto>>(HttpMethod.Get, RouteUri.UriWorkoutExercises);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Get WorkoutExercise");
            }
        }

        public void GetExercise(int workoutId)
        {
            try
            {
                var Client = ExecuteHttpClient;
                Exercises = WorkoutExercise.Where(w => w.WorkoutPlanId == workoutId)
                                            .Select(s => s.Exercise).ToList();
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Get Exercise");
            }
            
        }
    }
}

TrainingAppAspCore/Pages/WorkoutPlan.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TrainingAppAspCore.Dto;
using Microsoft.Extensions.Logging;

namespace TrainingAppAspCore.Pages
{
    public class WorkoutPlanModel : PageModel
    {
        IExecuteTrainingHttpClient ExecuteHttpClient;
        public List<WorkoutPlanDto> Workouts { get; set; }
        private ILogger _logger;

        public WorkoutPlanModel(IExecuteTrainingHttpClient executeTrainingClient, ILogger<WorkoutPlanModel> logger)
        {
            ExecuteHttpClient = executeTrainingClient;
            _logger = logger;
        }

        public async Task OnGet()
        {
            try
            {
                var Client = ExecuteHttpClient;
                Workouts = await Client.ExecuteRoute<List<WorkoutPlanDto>>(HttpMethod.Get, RouteUri.UriWorkoutPlans);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error in Get WorkoutPlan");
            }

        }
    }
}

TrainingAppAspCore/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

TrainingAppAspCore/Pages/ClientWorkouts.cshtml
@page
@model ClientWorkoutsModel


<div>
    <h3>@ViewData["Title"]</h3>

    @*when less than 3 workout then have Create Workout button*@
    @foreach (var workouts in Model.ClientWorkouts)
    {
        @Html.Partial("_ClientWorkoutPartial", workouts)
    }

    @{
        var numWorkouts = Model.ClientWorkouts.Count;
        var numCreateButton = 3 - numWorkouts;

        for (int i = 1; i <= numCreateButton; i++)
        {
            @Html.Partial("_CreateWorkoutPartial")
        }
    }
</div>

TrainingAppAspCore/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<environment include="Development">
    <link rel="stylesheet" href="~/css/backgroundBody.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="~/css/backgroundBody.min.css" asp-append-version="true" />
</environment>

<div class="contactBody" id="contactBody">
    <h2>@ViewData["Title"]</h2>
    <h3>@Model.MessageContact</h3>
    <p>
        <strong>Oliveira Apps</strong> - Bianca Oliveira
    </p>
    <address>
        <strong>Support:</strong> <a href="mailto:biancaoliveira.apps@gmail.com">biancaoliveira.apps@gmail.com</a><br />
    </address>

    <div id="contactFooter">
        <h2>About Oliveira Apps</h2>
        <p>@Model.MessageAbout</p>
    </div>
</div>

TrainingAppAspCore/Pages/CreateWorkout.cshtml
@page

@model CreateWorkoutModel
@{
    ViewData["Title"] = "Create a new Workout Plan";
    ViewData["Error"] = TempData["ErrorMessage"] ?? string.Empty;
}

<div id="workoutBody">
    <h2>Select a Workout that you want to add</h2>

    @foreach (var plan in Model.Workouts)
    {
        <div id="workoutGrid" class="col-sm-6 col-lg-6 col-md-6">
            <div class="thumbnail">
                <a asp-page="WorkoutExercise" asp-route-id="@plan.WorkoutPlanId" asp-route-frequency="frequency">
                    <img src="@plan.ImageUrl" class="img-responsive" alt="@plan.Name" />
                </a>
                <form asp-page-handler="AddWorkoutClient" method="post" asp-route-id="@plan.WorkoutPlanId">
                    <select class="form-control btn btn-info" name="frequency">
                        <option value="1">each day</option>
                        <option value="2">every second day</option>
                        <option value="7">each week</option>
                        <option value="14">every second week</option>
                    </select>
                    <button class="form-control btn btn-warning">Add</button>
                </form>
            </div>
        </div>
    }

</div>

TrainingAppAspCore/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Authentication.AzureADB2C.UI
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}



<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/Exercise1Pic.jpg" alt="Workout Plan Info" class="img-responsive" style="width:1150px;height:420px" ; />
            <div class="carousel-caption" role="option">
                <p>
                    Have a look at all the Workout Plans you can do.
                    <a class="btn btn-default" href="WorkoutPlan">
                        Workout Plans
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Stretch1Pic.jpeg" alt="Log Into Account" class="img-responsive" style="width:1150px;height:420px;" />
            <div class="carousel-caption" role="option">
                <p>
                    Get Started, Log into your account.
                    <a class="btn btn-default" asp-area="AzureADB2C" asp-controller="Account" asp-action="SignIn">Sign in</a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/ContactBanner.jpeg" alt="Contact" class="img-responsive" style="width:1150px;height:420px;" />
            <div class="carousel-caption" role="option">
                <p>
                    Contact us or want to know more about us.
                    <a class="btn btn-default" href="Contact">
                        Contact
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container-fluid" id="index-picture-links">
    <div class="row">
        <div class="col-md-4">
            <a target="_self" href="WorkoutPlan">
                <img src="~/images/weights2Pic.jpeg" class="img-responsive" alt="View all Workout plans">
                <div id="indexText" class="centered"><strong>Workout Plans</strong></div>
            </a>

        </div>

        @if (!User.Identity.IsAuthenticated)
         {
            <div class="col-md-4">
                <a asp-area="AzureADB2C" asp-controller="Account" asp-action="SignIn">
                    <img src="~/images/WeightLift.jpeg" class="img-responsive" alt="Log into your account">
                    <div id="indexText" class="centered"><strong>Log Into Account</strong></div>
                </a>
            </div>
        }else
        {
            <div class="col-md-4">
                <a asp-page="ClientWorkouts">
                    <img src="~/images/WeightLift.jpeg" class="img-responsive" alt="Your Workouts">
                    <div id="indexText" class="centered"><strong>Your Workouts</strong></div>
                </a>
            </div>
        }

        <div class="col-md-4">
            <a target="_self" href="Contact">
                <img src="~/images/RollMat.jpeg" class="img-responsive" alt="Contact">
                <div id="indexText" class="centered"><strong>Contact Us</strong></div>
            </a>
        </div>
    </div>
</div>

TrainingAppAspCore/Pages/Logout.cshtml
@page
@using Microsoft.AspNetCore.Authentication.AzureADB2C.UI
@model LogoutModel
@{
}
<p>user ?</p>
@if (!User.Identity.IsAuthenticated)
{
    <div class="col-md-4">
        <p>user has loged out</p>
        @*<img src="~/images/WeightLift.jpeg" class="img-responsive" alt="Log into your account"*@>


    </div>
}
else
{
    <p>user still loged in</p>
}

TrainingAppAspCore/Pages/StartExercises.cshtml
@page
@model StartExerciseModel
@{
    ViewData["Title"] = "It's Workout Time";
}

<body id="exerciseBody">
    <h3>@ViewData["Title"]</h3>
    <div id="exerciseContainer">

        @{ foreach (var exercise in Model.Exercises)
            {
                <div id="exerciseDivBlock">
                    <div id="startExercises" class="classDivForExercises"
                         style="color:tomato; font-size:x-large;" onclick="CompleteExercise(this)">
                        <i class="far fa-check-circle fa-3x"></i>
                    </div>
                    <div>
                        <a id="btnExercise" href=@exercise.VideoLibrary.VideoUrl role="button" class="btn btn-primary btn-block">@exercise.Name</a>
                    </div>
                    <div>
                        <i id="btnReps" class="fas fa-lg fa-gas-pump fa-pull-left fa-border"> 12</i>
                        <i id="btnWeight" class="fas fa-lg fa-dumbbell fa-pull-left fa-border"> 20</i>
                    </div>
                </div>
            }
        }
    </div>
</body>

<script>
    var CompleteExercise = function (buttonIndex) {
        buttonIndex.style = "color:green; font-size:x-large;";
    }

    //let exerciseDivs = document.getElementsByClassName("classDivForExercises");
    //console.log(exerciseDivs);
</script>

TrainingAppAspCore/Pages/WorkoutExercise.cshtml
@page "{id?}"
@model WorkoutExerciseModel
@{
    ViewData["Title"] = "Exercises";
}

<div>
    <h3>@ViewData["Title"]</h3>

    @{ 
        int exId = int.Parse(PageContext.RouteData.Values["id"].ToString());
    }

    @{
        Model.GetExercise(@exId); 
    }

    @foreach (var exercise in Model.Exercises)
    {
        @Html.Partial("_ExercisesPartial", exercise)    
    }
</div>

TrainingAppAspCore/Pages/WorkoutPlan.cshtml
@page
@model WorkoutPlanModel
@{
    ViewData["Title"] = "View All Workout Plans";
}

<div id="workoutBody">
    <h2>Check out what we have for you in our <strong>Workout Plans</strong></h2>

        @foreach (var plan in Model.Workouts)
    {
        @Html.Partial("_WorkoutPlansPartial", plan) 
    }
</div>